---
# tasks file for rpi-nextcloud
- name: Log on which Linux distro Docker is going to be installed
  debug:
    msg: "The distro is: {{ ansible_distribution|lower }} and the version name is: {{ ansible_distribution_release }}"

- name: Install needed packages for Jessie or newer (see https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    allow_unauthenticated: true
    state: latest

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  ignore_errors: true

- name: Add Docker apt repo (as shown in step 4 of https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository in armhf)
  shell: |
    echo "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution|lower }} \
    {{ ansible_distribution_release }} stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list
  become: true

- name: Install Docker apt package
  apt:
    pkg: docker-ce
    state: latest
    update_cache: yes

- name: Install pip
  apt:
    name:
      - python-pip
      - python-setuptools
    state: latest

- name: Install Docker Compose
  pip:
    name: docker-compose

- name: add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: true


